### PR TITLE
Fix parsing arguments, use typehint

### LINKED ISSUE #121: Panic when parsing argument
The goal of this task is to make the following code in overflow more robust and tested.

[1]https://github.com/bjartek/overflow/blob/b089c0fa9da55d1ad691b396a46ce24fdb4b2ad6/state.go#L226

Cadence is an interpreted language and a transactions head looks like this

```swift
transaction(numberArg:UInt64, anotherNumberArg:Int64, stringArgument:String, charArgument:Character)
```

When sending in arguments we collect them as a map of string to interface{}.

Some corner cases:
 - there are many numeric types in cadence (cadence-lang.org) but we would like a simple number in go to work for all of them. So in the above example if i send in `42` to either numberArg or anotherNumberArg i want them to both work.
 - atm we have to use `overflow.WithAddress` to handle sending in an address as a string resolving from flowkit.State

Bonus:
 - support sending in arguments as cadence argument json spec from the onflow/flow-cli repo as an alternative

DoD:
There is a method to parse arguments into a result object

### PR DESCRIPTION
**Pull request by bjartek**
Closes #121 

## Description

______

For contributor use:

- [ ] Targeted PR against `main` branch
- [ ] Code follows the [standards mentioned here](https://github.com/bjartek/overflow/blob/main/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation
- [ ] Re-reviewed `Files changed` in the Github PR explorer

### CODE REVIEW

File: state.go [hunk 1]
```diff
@@ -284,72 +277,31 @@ func (o *OverflowState) parseArguments(fileName string, code []byte, inputArgs m
...
-		if interErr != nil {
-			return nil, nil, interErr
-		}
-		value, err := runtime.ParseLiteral(argumentString, semaType, inter)
+	args, err := ExtractArguments(fileName, code, inputArgs)
+	if err != nil {
+		return nil, nil, errors.Wrap(err, "extracting arguments")
+	}
+	for _, oa := range args {
+		// todo multierr
```
Comment (willsu88) [inline state.go]: can we handle this now?

File: state.go [hunk 2]
```diff
@@ -388,6 +340,39 @@ func (o *OverflowState) Address(key string) string {
...
+	for _, flowDeploymentContract := range flowDeploymentContracts {
+		if flowDeploymentContract.Name == key {
+			return &flowDeploymentContract.AccountAddress, nil
+		}
+	}
+	return nil, fmt.Errorf("Not valid user account, contract or deployment contract")
+}
+
 // return the flow Address of the given name
 func (o *OverflowState) FlowAddress(key string) flow.Address {
```
Comment (willsu88) [inline state.go:376]: do we still need this function now that we have FlowAddressE ?

Comment (willsu88) [reply state.go:376]: it seems like it's only used by the `func (o *OverflowState) Address(key string) string`  function.

Comment (bjartek) [reply state.go:376]: This api is used to other packages as well so i am hesitant to remove it.

File: state.go (hunk 1 above)
Comment (bjartek) [reply state.go]: fixed in 5629e99

Comment (willsu88) [reply state.go]: nice!

File: state.go (hunk 2 above)
Comment (willsu88) [reply state.go:376]: ah okay i see. prob better to keep it for now then. but might be good to leave a comment to differentiate between these two or note that FlowAddress is used elsewhere

File: parse_parameters_test.go [hunk 3]
```diff
@@ -0,0 +1,148 @@
...
+		wantErr autogold.Value
+		name    string
+		args    Args
+	}
+
+	tests := []TestInput{
+		{
+			name: "64bit integers",
+			args: Args{
+				code:      "u:UInt64, i:Int64",
```
Comment (gabrielseibel1) [inline parse_parameters_test.go]: are we expected to handle variations of this wrt the spacing? e.g. `code: "u : UInt64, i: Int64"`

File: parse_parameters_test.go [hunk 4]
```diff
@@ -0,0 +1,148 @@
...
+				inputArgs: map[string]interface{}{"u": 42, "i": 42},
```
Comment (gabrielseibel1) [inline parse_parameters_test.go]: would it be interesting to define behavior (error?) if provided arg does not fit type? e.g. a test with `inputArgs: map[string]interface{}{"u": -42, "i": -42}`

File: setup.go [hunk 5]
```diff
@@ -175,8 +175,21 @@ func (o *OverflowBuilder) StartResult() *OverflowState {
...
+			adr, err2 := hexToAddress(name)
+			if err2 == nil {
+				return adr.String(), nil
+			}
+
+			address, err2 := overflow.FlowAddressE(name)
+			if err2 != nil {
+				return "", errors.Wrapf(err2, "could not parse %s into an address", name)
+			}
+			return address.HexWithPrefix(), nil
```
Comment (gabrielseibel1) [inline setup.go:192]: should this be provided by overflow as a default or just exported func?

File: state.go [hunk 6]
```diff
@@ -388,6 +341,39 @@ func (o *OverflowState) Address(key string) string {
 	return fmt.Sprintf("0x%s", o.FlowAddress(key))
 }
 
+// return the flow Address of the given name
+func (o *OverflowState) FlowAddressE(key string) (*flow.Address, error) {
```
Comment (gabrielseibel1) [inline state.go:342]: what does the E stand for?

File: parse_parameters_test.go (hunk 3 above)
Comment (bjartek) [reply parse_parameters_test.go]: i am not sure if these tests are needed here at all anymore, since this logic now happends in underflow and they are already tested there. What do you think?

File: state.go [hunk 7]
```diff
@@ -388,6 +341,39 @@ func (o *OverflowState) Address(key string) string {
...
+	if err != nil {
+		return nil, err
+	}
+
+	for _, flowDeploymentContract := range flowDeploymentContracts {
+		if flowDeploymentContract.Name == key {
+			return &flowDeploymentContract.AccountAddress, nil
+		}
+	}
+	return nil, fmt.Errorf("Not valid user account, contract or deployment contract")
```
Comment (gabrielseibel1) [inline state.go]: could use `errors.New`

File: state.go [hunk 8]
```diff
@@ -156,7 +156,7 @@ type OverflowState struct {
 
 type OverflowArgument struct {
 	Value interface{}
-	Type  ast.Type
+	Type  sema.Type
```
Comment (gabrielseibel1) [inline state.go:159]: Could you briefly explain this change?

File: setup.go (hunk 5 above)
Comment (bjartek) [reply setup.go:192]: this should be the default, other implementations are really only there for testing.

File: state.go (hunk 6 above)
Comment (bjartek) [reply state.go:342]: Since golang does not support overloading i tend to just add the E suffix at the end of a method that returns whatever the original method does and an Error.

File: state.go (hunk 7 above)
Comment (bjartek) [reply state.go]: Can you try to use the suggest feature to add this comment so that the overhead of fixing it is not high?

File: state.go (hunk 6 above)
Comment (gabrielseibel1) [reply state.go:342]: ooooh right

File: state.go (hunk 8 above)
Comment (bjartek) [reply state.go:159]: the ast type is not usefull to us but the sema type is. the api in flow expects the sema type and not the ast type basically.

File: parse_parameters_test.go (hunk 4 above)
Comment (bjartek) [reply parse_parameters_test.go]: see the above comment

File: state.go (hunk 8 above)
Comment (bjartek) [reply state.go:159]: underflow as a library do not have the responsibility of creating the program and checker so it does not have a way to do the convertion itself.

**Review by willsu88 — APPROVED** [review]
looks good on my end. i'll leave to @gabrielseibel1 to see if he has any other comments he wants to resolve or mention

File: state.go (hunk 7 above)
Comment (gabrielseibel1) [inline state.go]:
```suggestion
	return nil, errors.New("Not valid user account, contract or deployment contract")
```

**Review by gabrielseibel1 — APPROVED** [review]

File: state.go (hunk 7 above)
Comment (gabrielseibel1) [reply state.go]: this apparently is outdated ill just cancel it

File: parse_parameters_test.go (hunk 3 above)
Comment (gabrielseibel1) [reply parse_parameters_test.go]: yes this is not the place to test it as we've discussed the coverage is maintained by removing it and it's really an underflow test

File: parse_parameters_test.go (hunk 4 above)
Comment (gabrielseibel1) [reply parse_parameters_test.go]: should be underflow test instead if at all so nvm
